### ISSUE TITLE
Negative entropy which is very strange 

### ISSUE THREAD

**Issue by vvaghu** [mutualinfo/mutual_info#1]
Hi,

I have tested your entropy and mutual information methods and got negative entropy result. I consider this as wrong result. Do you have any explanation for this bug ?
I am attaching data that I used for the entropy test.
[negative_entropy_data.zip](https://github.com/mutualinfo/mutual_info/files/6777204/negative_entropy_data.zip)

**Comment by cottrell** [comment]
@vvaghu I basically just copied https://gist.github.com/GaelVaroquaux/ead9898bd3c973c40429 into here and then I think I might have started to clean some things up ... It's been a while but if I remember correctly I had the same question the first time I hit this. 

I think this is actually differential entropy which can be negative https://en.wikipedia.org/wiki/Differential_entropy

There are some weird dimensional inconsistencies in some of these definitions as well. 

I think all of these confusing things should go in the README.md because everytime I come back to this I've forgotten them.

If you are digging into this and want to contribute let me know. Like I said I basically just copied the gist into here so that everyone could kick back there updates/improvments rather than having a thousand gist forks.

**Comment by cottrell** [comment]
Have updated the docs a bit, let me know if you end up digging around or finding bugs improvements. I forget nearly all of this stuff until I start to use it again.

**Comment by braniii** [comment]
Hi, to follow up on this discussion. The reason that the entropies of continuous variables can be negative is that taking the limit $|\mathcal{X}|\to\infty$, the Shannon entropy $H(X) = \sum_{x\in\mathcal{X}} p_x \ln p_x$ **does not converge** to $H(X) = \int \mathrm{d}x p(x) \ln p(x)$. The probability density is a dimensional quantity, and therefore the logarithm of it, $\ln p(x)$, is not defined. Changing the units changes the values.

For anyone who actually needs to estimate a normalized mutual information and it is not enough to know why the Kraskov estimator fails: I've recently published an article, [arXiv:2405.04980](https://arxiv.org/abs/2405.04980), where I discuss this issue in detail and present a generalization of the Kraskov estimator that is able to estimate normalized mutual information as well. The source code is available on github at [moldyn/NorMI](https://github.com/moldyn/NorMI).

**Comment by cottrell** [comment]
> Hi, to follow up on this discussion. The reason that the entropies of continuous variables can be negative is that taking the limit |X|→∞, the Shannon entropy H(X)=∑x∈Xpxln⁡px **does not converge** to H(X)=∫dxp(x)ln⁡p(x). The probability density is a dimensional quantity, and therefore the logarithm of it, ln⁡p(x), is not defined. Changing the units changes the values.
> 
> For anyone who actually needs to estimate a normalized mutual information and it is not enough to know why the Kraskov estimator fails: I've recently published an article, [arXiv:2405.04980](https://arxiv.org/abs/2405.04980), where I discuss this issue in detail and present a generalization of the Kraskov estimator that is able to estimate normalized mutual information as well. The source code is available on github at [moldyn/NorMI](https://github.com/moldyn/NorMI).

This looks nice, will update the README in case people are still landing here.
